server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://120.79.210.91:3306/task_sys?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000
  aop:
    proxy-target-class: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
      port: 6379
      host: 120.79.210.91
      lettuce:
        pool:
          min-idle: 50
          max-idle: 256
          max-active: 1000
      database: 0
      timeout: 10s


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    use-generated-keys: true
#分页设置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
#mybatis打印sql语句
logging:
  level:
    com.chuncongcong.task: debug


#图片上传存储路径
upload:
  file:
    portrait: /upload/img/
    task: /upload/task/
    message: /upload/message/


#session过期时间
token:
  timeout: 3600
