package com.chuncongcong.task.dao.mapper;

import com.chuncongcong.task.model.entity.MessageBoard;

public interface MessageBoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_board
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_board
     *
     * @mbg.generated
     */
    int insert(MessageBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_board
     *
     * @mbg.generated
     */
    int insertSelective(MessageBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_board
     *
     * @mbg.generated
     */
    MessageBoard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_board
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MessageBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_board
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MessageBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_board
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MessageBoard record);
}