package com.chuncongcong.task.dao.mapper;

import com.chuncongcong.task.model.entity.TaskUpdate;

public interface TaskUpdateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_update
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_update
     *
     * @mbg.generated
     */
    int insert(TaskUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_update
     *
     * @mbg.generated
     */
    int insertSelective(TaskUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_update
     *
     * @mbg.generated
     */
    TaskUpdate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_update
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_update
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskUpdate record);
}