package com.chuncongcong.task.dao.mapper;

import com.chuncongcong.task.model.entity.TaskUser;

public interface TaskUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated
     */
    int insert(TaskUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated
     */
    int insertSelective(TaskUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated
     */
    TaskUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskUser record);
}