package com.chuncongcong.task.model.entity;

import com.chuncongcong.task.model.constants.ReadType;
import com.chuncongcong.task.model.constants.SignType;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MessageBoard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_board.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_board.parent_id
     *
     * @mbg.generated
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_board.from_user_id
     *
     * @mbg.generated
     */
    private Long fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_board.to_user_id
     *
     * @mbg.generated
     */
    private Long toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_board.is_read
     *
     * @mbg.generated
     */
    private ReadType isRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_board.sign
     *
     * @mbg.generated
     */
    private SignType sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_board.ext_file
     *
     * @mbg.generated
     */
    private String extFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_board.create_time
     *
     * @mbg.generated
     */
    private Instant createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_board.update_time
     *
     * @mbg.generated
     */
    private Instant updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_board.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_board.message
     *
     * @mbg.generated
     */
    private String message;
}