package com.chuncongcong.task.model.entity;

import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MessageDrift {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_drift.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_drift.from_user_id
     *
     * @mbg.generated
     */
    private Long fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_drift.ext_file
     *
     * @mbg.generated
     */
    private String extFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_drift.create_time
     *
     * @mbg.generated
     */
    private Instant createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_drift.update_time
     *
     * @mbg.generated
     */
    private Instant updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_drift.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_drift.to_user
     *
     * @mbg.generated
     */
    private String toUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_drift.message
     *
     * @mbg.generated
     */
    private String message;
}