package com.chuncongcong.task.model.entity;

import com.chuncongcong.task.model.constants.SignType;
import com.chuncongcong.task.model.constants.TaskCurrentState;
import com.chuncongcong.task.model.constants.TaskLevel;
import com.chuncongcong.task.model.constants.TaskSubmitState;
import com.chuncongcong.task.model.constants.TaskType;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.parent_id
     *
     * @mbg.generated
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.start_time
     *
     * @mbg.generated
     */
    private Instant startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.end_time
     *
     * @mbg.generated
     */
    private Instant endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.total_time
     *
     * @mbg.generated
     */
    private Integer totalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.distance_end_time
     *
     * @mbg.generated
     */
    private Integer distanceEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_level
     *
     * @mbg.generated
     */
    private TaskLevel taskLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.sign
     *
     * @mbg.generated
     */
    private SignType sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_current_state
     *
     * @mbg.generated
     */
    private TaskCurrentState taskCurrentState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_submit_state
     *
     * @mbg.generated
     */
    private TaskSubmitState taskSubmitState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.ext_file
     *
     * @mbg.generated
     */
    private String extFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_time
     *
     * @mbg.generated
     */
    private Instant createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.update_time
     *
     * @mbg.generated
     */
    private Instant updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_type
     *
     * @mbg.generated
     */
    private TaskType taskType;
}