package com.chuncongcong.task.model.entity;

import com.chuncongcong.task.model.constants.TaskPosition;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TaskUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_user.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_user.task_id
     *
     * @mbg.generated
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_user.task_position
     *
     * @mbg.generated
     */
    private TaskPosition taskPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_user.create_time
     *
     * @mbg.generated
     */
    private Instant createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_user.update_time
     *
     * @mbg.generated
     */
    private Instant updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_user.state
     *
     * @mbg.generated
     */
    private Byte state;
}